### ISSUE TITLE
About 'wp scaffold vccw'

### ISSUE THREAD

**Issue by GotoKazu** [vccw-team/scaffold-vccw#2]
Hello!
Thank you for having `--lang` be able to choose.
It will be an error if the latest version of Japanese is not released, so I am glad that you can choose the version with future updates as well.
First of all, is this the lang and version part of WordPress Settings at site.yml?
Since I had nothing to do with Github and others, I dared to comment.

こんにちは！
--langが選べるようにしてもらってありがとうございます。
日本語の最新版がリリースされていないとエラーになるので今後のアップデートでバージョンも選べるとなお嬉しいです。
そもそもこれって site.yml でのWordPress Settings のlang とversion 部分でしょうかね。スルーでも大丈夫です。
Github やその他でこのような取り組みと絡んだことがなかったのであえてコメントいれてみました。英語だめなんでGoogle翻訳です。すみません。

**Comment by miya0001** [comment]
WP-CLI team already know about the problem. 
Actually, the problem should be solved in the WordPress core or the WP-CLI core.

Please see following issue.
https://github.com/wp-cli/wp-cli/issues/3783

Personally, I recommend don't use `--lang` option for now.
Then run following.

```
$ wp core language install ja --activate
$ wp plugin install wp-multibyte-patch --activate
$ wp option update timezone_string $(wp eval "echo _x( '0', 'default GMT offset or timezone string' );")
$ wp option update date_format $(wp eval "echo __( 'M jS Y' );")
```

If you do them, it will be same with Japanese package.

Thanks! 😄
