### ISSUE TITLE
Customization of vccw.yml.mustache

### ISSUE THREAD

**Issue by marushu** [vccw-team/scaffold-vccw#4]
Thank you grate advice!!

I would like to change the database host to IP value.
How can I customize vccw.yml.mustache so that the host of the database can also be changed?

**Comment by miya0001** [comment]
It is mine for example.

```
# encoding: utf-8
# vim: ft=ruby expandtab shiftwidth=2 tabstop=2

hostname: {{ host }}
ip: {{ ip }}
version: latest
lang: {{ lang }}
db_host: {{ ip }}
theme: ''

theme_unit_test: false
theme_unit_test_uri: https://raw.githubusercontent.com/WPTRT/theme-unit-test/master/themeunittestdata.wordpress.xml
#theme_unit_test_uri: https://raw.githubusercontent.com/jawordpressorg/theme-test-data-ja/master/wordpress-theme-test-date-ja.xml

wp_i18n_tools: false
mailcatcher: false
plugins: []
wp_cli_packages: []
npms: []
composers: []
ruby_gems: []
```

**Comment by marushu** [comment]
I tried host: {{ip}}, but it did not seem to be reflected in site.yml.
Is the setting of ~ /. vccw / config.yml reflected in scaffold vccw?
Also, I would like to use Linked Clone.

Do we need to make substantial changes to be able to handle all the normal site.yml settings?

**Comment by marushu** [comment]
Sorry, host: {{ ip }} is mistake.
db_host: {{ ip }} is true.

**Comment by miya0001** [comment]
It is working for me. I guess you are making mistakes, for example wrong filename or so.
Thanks!

**Comment by marushu** [comment]
Oh... Thank you I try again. :)

**Comment by marushu** [comment]
I successed db_host and linked clone options.
Thank you so much!!

Then I'm trying make theme using provision-post.sh. :)
